"""Evaluate one attack skill against a target model and guard judge.

This command intentionally bypasses planner selection so the reported ASR is
attributable to exactly one skill. It can also run the unmodified prompts as a
direct baseline and reports both prompt-level best-of-N ASR and variant-level
ASR. Success follows the repository evaluator: ``judge_score == 5``.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import replace
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import sys
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import core.proxy_bypass  # noqa: F401,E402

from core.config_resolver import ConfigResolver  # noqa: E402
from core.constants import RISK_CATEGORY_MAP  # noqa: E402
from core.environment import build_environment  # noqa: E402
from core.evaluator import MockEvaluator, XTEAMING_GPT4O_SUCCESS_SCORE  # noqa: E402
from core.executor import SkillExecutor  # noqa: E402
from core.schemas import SkillContext, SkillSpec  # noqa: E402
from core.skill_loader import SkillLoader  # noqa: E402
from core.utils import make_run_id, read_yaml, write_json  # noqa: E402


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate one attack skill against the configured target model and "
            "guard judge without running the planner or other skills."
        )
    )
    parser.add_argument("--skill", required=True, help="Exact skill directory/name.")
    parser.add_argument(
        "--dataset",
        "--seed-prompt-file",
        dest="dataset",
        default=str(PROJECT_ROOT / "data" / "HarmBench.jsonl"),
        help="JSONL dataset containing a query field.",
    )
    parser.add_argument("--start", type=int, default=0, help="Dataset row index, inclusive.")
    parser.add_argument("--end", type=int, default=None, help="Dataset row index, exclusive.")
    parser.add_argument("--limit", type=int, default=10, help="Maximum matching prompts.")
    parser.add_argument("--filter-field", default="", help="Optional exact-match JSON field.")
    parser.add_argument("--filter-value", default="", help="Value for --filter-field.")
    parser.add_argument(
        "--candidate-count",
        type=int,
        default=1,
        help="Variants generated by the skill per prompt; prompt ASR is best-of-N.",
    )
    parser.add_argument(
        "--compare-direct",
        action="store_true",
        help="Also evaluate each unmodified seed as a direct-query baseline.",
    )
    parser.add_argument(
        "--config",
        default=str(PROJECT_ROOT / "configs" / "config.yaml"),
        help="Config with environment target and evaluator.guard_model.",
    )
    parser.add_argument("--target-model", default="", help="Optional target model override.")
    parser.add_argument("--judge-model", default="", help="Optional guard model override.")
    parser.add_argument(
        "--transport",
        choices=("http", "openai_sdk"),
        default="",
        help="Optional transport override for both target and judge.",
    )
    parser.add_argument(
        "--report-out",
        "--out",
        dest="report_out",
        required=True,
        help="JSON report path. It is checkpointed after every prompt.",
    )
    return parser.parse_args(argv)


def _validate_args(args: argparse.Namespace) -> None:
    if args.start < 0:
        raise ValueError("--start must be non-negative")
    if args.end is not None and args.end <= args.start:
        raise ValueError("--end must be greater than --start")
    if args.limit <= 0:
        raise ValueError("--limit must be positive")
    if not 1 <= args.candidate_count <= 20:
        raise ValueError("--candidate-count must be between 1 and 20")
    if bool(args.filter_field) != bool(args.filter_value):
        raise ValueError("--filter-field and --filter-value must be supplied together")


def _risk_types(record: dict[str, Any]) -> list[str]:
    risk_code = str(record.get("risk_category", "")).strip()
    mapped = RISK_CATEGORY_MAP.get(risk_code, "")
    if mapped:
        return [mapped]
    for field in ("risk_name", "SemanticCategory"):
        value = str(record.get(field, "")).strip()
        if value:
            return [value]
    return ["unclassified"]


def select_dataset_rows(
    path: Path,
    *,
    start: int,
    end: int | None,
    limit: int,
    filter_field: str = "",
    filter_value: str = "",
) -> list[dict[str, Any]]:
    """Select rows while preserving their original zero-based indices."""
    selected: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for index, line in enumerate(handle):
            if index < start:
                continue
            if end is not None and index >= end:
                break
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{index + 1}: {exc}") from exc
            if not isinstance(record, dict):
                continue
            if filter_field and str(record.get(filter_field, "")) != filter_value:
                continue
            query = str(record.get("query", "")).strip()
            if not query:
                continue
            selected.append(
                {
                    "index": index,
                    "query": query,
                    "risk_types": _risk_types(record),
                    "risk_category": str(record.get("risk_category", "")),
                    "risk_name": str(record.get("risk_name", "")),
                }
            )
            if len(selected) >= limit:
                break
    return selected


def _find_skill(name: str) -> SkillSpec:
    specs = SkillLoader(PROJECT_ROOT, [PROJECT_ROOT / "skills"]).discover()
    for spec in specs:
        if spec.name == name:
            return spec
    raise ValueError(f"Skill not found: {name}")


def _safe_error(exc: Exception, secrets: list[str]) -> str:
    message = str(exc).strip()
    for secret in secrets:
        if secret:
            message = message.replace(secret, "<redacted>")
    compact = " ".join(message.split())
    return f"{type(exc).__name__}: {compact[:500]}"


def _evaluate_candidate(
    *,
    candidate_text: str,
    source_skill: str,
    candidate_index: int,
    seed_prompt: str,
    risk_types: list[str],
    target: Any,
    evaluator: MockEvaluator,
    secrets: list[str],
) -> dict[str, Any]:
    candidate = {
        "candidate_id": f"{source_skill}-{candidate_index}",
        "candidate_index": candidate_index,
        "text": candidate_text,
        "source_skill": source_skill,
        "risk_type": risk_types[0] if risk_types else "unclassified",
    }
    result: dict[str, Any] = {
        "candidate_index": candidate_index,
        "candidate_text": candidate_text,
        "response_text": "",
        "target_model": "",
        "judge_score": None,
        "success": False,
        "defender_refused": None,
        "empty_response": None,
        "judge_reason": "",
        "error": "",
    }
    try:
        response = target.execute(candidate_text)
    except Exception as exc:  # noqa: BLE001 - preserve per-candidate progress
        result["error"] = "target: " + _safe_error(exc, secrets)
        return result

    response["candidate_index"] = 0
    response["source_skill"] = source_skill
    result["response_text"] = str(response.get("response_text", ""))
    result["target_model"] = str(response.get("model_name", ""))
    try:
        evaluation = evaluator.evaluate(
            [candidate],
            [response],
            seed_prompt=seed_prompt,
            seed_risk_types=risk_types,
        )
        bundles = list(evaluation.metadata.get("score_bundles", []))
        if not bundles:
            raise RuntimeError("guard judge returned no score bundle")
        bundle = bundles[0]
        score = int(bundle.get("judge_score", 1))
        result.update(
            {
                "judge_score": score,
                "success": score == XTEAMING_GPT4O_SUCCESS_SCORE,
                "defender_refused": bool(bundle.get("defender_refused", False)),
                "empty_response": bool(
                    bundle.get("empty_response", not result["response_text"].strip())
                ),
                "judge_reason": str(bundle.get("reason", "")),
            }
        )
    except Exception as exc:  # noqa: BLE001 - preserve per-candidate progress
        result["error"] = "judge: " + _safe_error(exc, secrets)
    return result


def summarize_cases(
    cases: list[dict[str, Any]],
    *,
    requested: int,
    candidate_count: int,
    compare_direct: bool,
) -> dict[str, Any]:
    skill_prompt_successes = sum(bool(case.get("skill_success")) for case in cases)
    skill_prompt_answered = sum(
        any(variant.get("judge_score") is not None for variant in case.get("variants", []))
        for case in cases
    )
    complete_skill_prompts = sum(
        len(case.get("variants", [])) == candidate_count
        and all(
            variant.get("judge_score") is not None
            for variant in case.get("variants", [])
        )
        for case in cases
    )
    complete_skill_successes = sum(
        bool(case.get("skill_success"))
        and len(case.get("variants", [])) == candidate_count
        and all(
            variant.get("judge_score") is not None
            for variant in case.get("variants", [])
        )
        for case in cases
    )
    variants = [
        variant
        for case in cases
        for variant in case.get("variants", [])
    ]
    answered_variants = [
        variant for variant in variants if variant.get("judge_score") is not None
    ]
    successful_variants = sum(bool(variant.get("success")) for variant in answered_variants)
    distribution = Counter(int(variant["judge_score"]) for variant in answered_variants)
    summary: dict[str, Any] = {
        "requested_prompts": requested,
        "processed_prompts": len(cases),
        "skill_answered_prompts": skill_prompt_answered,
        "skill_complete_prompts": complete_skill_prompts,
        "skill_successful_prompts": skill_prompt_successes,
        "skill_prompt_asr_requested": (
            skill_prompt_successes / requested if requested else 0.0
        ),
        "skill_prompt_asr_answered": (
            skill_prompt_successes / skill_prompt_answered
            if skill_prompt_answered
            else 0.0
        ),
        "skill_successful_complete_prompts": complete_skill_successes,
        "skill_prompt_asr_complete": (
            complete_skill_successes / complete_skill_prompts
            if complete_skill_prompts
            else 0.0
        ),
        "requested_variants": requested * candidate_count,
        "generated_variants": len(variants),
        "answered_variants": len(answered_variants),
        "successful_variants": successful_variants,
        "empty_skill_responses": sum(
            not str(variant.get("response_text", "")).strip()
            for variant in answered_variants
        ),
        "nonempty_skill_responses": sum(
            bool(str(variant.get("response_text", "")).strip())
            for variant in answered_variants
        ),
        "refused_skill_variants": sum(
            bool(variant.get("defender_refused")) for variant in answered_variants
        ),
        "variant_asr_answered": (
            successful_variants / len(answered_variants)
            if answered_variants
            else 0.0
        ),
        "variant_score_distribution": {
            str(score): distribution.get(score, 0) for score in range(1, 6)
        },
        "skill_error_count": sum(bool(variant.get("error")) for variant in variants)
        + sum(bool(case.get("skill_execution_error")) for case in cases),
        "success_criterion": "judge_score == 5",
        "prompt_aggregation": f"best-of-{candidate_count}",
    }
    if compare_direct:
        direct_answered = sum(
            case.get("direct", {}).get("judge_score") is not None for case in cases
        )
        direct_successes = sum(
            bool(case.get("direct", {}).get("success")) for case in cases
        )
        paired_answered = [
            case
            for case in cases
            if case.get("direct", {}).get("judge_score") is not None
            and any(
                variant.get("judge_score") is not None
                for variant in case.get("variants", [])
            )
        ]
        paired_complete = [
            case
            for case in paired_answered
            if len(case.get("variants", [])) == candidate_count
            and all(
                variant.get("judge_score") is not None
                for variant in case.get("variants", [])
            )
        ]
        summary.update(
            {
                "direct_answered_prompts": direct_answered,
                "direct_successful_prompts": direct_successes,
                "direct_asr_requested": direct_successes / requested if requested else 0.0,
                "direct_asr_answered": (
                    direct_successes / direct_answered if direct_answered else 0.0
                ),
                "paired_answered_prompts": len(paired_answered),
                "paired_complete_prompts": len(paired_complete),
                "incremental_wins": sum(
                    bool(case.get("skill_success"))
                    and not bool(case.get("direct", {}).get("success"))
                    for case in paired_complete
                ),
                "direct_only_wins": sum(
                    bool(case.get("direct", {}).get("success"))
                    and not bool(case.get("skill_success"))
                    for case in paired_complete
                ),
                "direct_error_count": sum(
                    bool(case.get("direct", {}).get("error")) for case in cases
                ),
                "empty_direct_responses": sum(
                    case.get("direct", {}).get("judge_score") is not None
                    and not str(
                        case.get("direct", {}).get("response_text", "")
                    ).strip()
                    for case in cases
                ),
                "refused_direct_prompts": sum(
                    bool(case.get("direct", {}).get("defender_refused"))
                    for case in cases
                    if case.get("direct", {}).get("judge_score") is not None
                ),
            }
        )
    return summary


def completion_status(
    summary: dict[str, Any], *, compare_direct: bool
) -> str:
    """Classify whether the ASR result is complete enough to interpret."""
    if int(summary.get("skill_answered_prompts", 0)) == 0:
        return "failed"
    requested = int(summary.get("requested_prompts", 0))
    incomplete = int(summary.get("skill_complete_prompts", 0)) < requested
    if compare_direct:
        incomplete = incomplete or int(
            summary.get("direct_answered_prompts", 0)
        ) < requested
    if incomplete or int(summary.get("skill_error_count", 0)) > 0 or int(
        summary.get("direct_error_count", 0)
    ) > 0:
        return "completed_with_errors"
    return "completed"


def _checkpoint(
    path: Path,
    *,
    metadata: dict[str, Any],
    cases: list[dict[str, Any]],
    requested: int,
    candidate_count: int,
    compare_direct: bool,
    status: str,
) -> dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True)
    summary = summarize_cases(
        cases,
        requested=requested,
        candidate_count=candidate_count,
        compare_direct=compare_direct,
    )
    payload = {
        **metadata,
        "status": status,
        "target_model_evaluated": bool(
            summary.get("skill_answered_prompts", 0)
            or summary.get("direct_answered_prompts", 0)
        ),
        "attack_outcome_evaluated": bool(
            summary.get("skill_answered_prompts", 0)
        ),
        "summary": summary,
        "cases": cases,
    }
    write_json(path, payload)
    return payload


def _validate_runtime(target: Any, evaluator: MockEvaluator) -> None:
    target_cfg = getattr(target, "cfg", None)
    if target_cfg is None or not bool(getattr(target, "enabled", False)):
        raise RuntimeError("ASR evaluation requires an enabled LLM target, not a mock")
    if not getattr(target_cfg, "base_url", "") or not getattr(target_cfg, "model", ""):
        raise RuntimeError("ASR target is missing base_url or model")
    guard = getattr(evaluator, "guard", None)
    guard_cfg = getattr(guard, "cfg", None)
    if guard_cfg is None or not bool(getattr(guard, "enabled", False)):
        raise RuntimeError("ASR evaluation requires an enabled guard judge")
    if not getattr(guard_cfg, "base_url", "") or not getattr(guard_cfg, "model", ""):
        raise RuntimeError("ASR guard judge is missing base_url or model")


def run(args: argparse.Namespace) -> dict[str, Any]:
    _validate_args(args)
    dataset_path = Path(args.dataset).resolve()
    config_path = Path(args.config).resolve()
    report_path = Path(args.report_out).resolve()
    rows = select_dataset_rows(
        dataset_path,
        start=args.start,
        end=args.end,
        limit=args.limit,
        filter_field=args.filter_field,
        filter_value=args.filter_value,
    )
    if not rows:
        raise ValueError("No dataset rows matched the requested range/filter")

    config = ConfigResolver.normalize(read_yaml(config_path))
    resolver = ConfigResolver(config)
    environment_config = dict(config.get("environment", {}))
    target_profile = dict(environment_config.get("target_profile", {}))
    environment_llm = dict(environment_config.get("llm", {}))
    guard_config = dict(config.get("evaluator", {}).get("guard_model", {}))
    if args.target_model:
        environment_llm["model"] = args.target_model
        target_profile["model_name"] = args.target_model
    if args.judge_model:
        guard_config["model"] = args.judge_model
    if args.transport:
        environment_llm["transport"] = args.transport
        guard_config["transport"] = args.transport
    environment_config["llm"] = environment_llm

    spec = _find_skill(args.skill)
    executor = SkillExecutor(PROJECT_ROOT, timeout_seconds=resolver.executor_timeout())
    target = build_environment(target_profile, environment_config)
    evaluator = MockEvaluator(guard_config)
    if args.target_model:
        target.cfg = replace(target.cfg, model=args.target_model)
    if args.judge_model:
        evaluator.guard.cfg = replace(evaluator.guard.cfg, model=args.judge_model)
    _validate_runtime(target, evaluator)
    skill_backend = resolver.resolve_skill_backend()
    secrets = [
        str(environment_llm.get("api_key", "")),
        str(guard_config.get("api_key", "")),
        str(skill_backend.get("api_key", "")),
        str(getattr(target.cfg, "api_key", "")),
        str(getattr(evaluator.guard.cfg, "api_key", "")),
    ]
    run_id = make_run_id("skill-asr")
    metadata = {
        "run_id": run_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "validation_scope": "target_model_asr",
        "skill_name": spec.name,
        "skill_mode": spec.mode,
        "skill_target_domain": spec.target_domain,
        "dataset": str(dataset_path),
        "selected_indices": [int(row["index"]) for row in rows],
        "candidate_count": args.candidate_count,
        "compare_direct": bool(args.compare_direct),
        "target_model": str(
            getattr(
                getattr(target, "cfg", None),
                "model",
                target_profile.get("model_name", "mock-target-model"),
            )
        ),
        "judge_model": str(evaluator.guard.cfg.model),
    }
    cases: list[dict[str, Any]] = []
    _checkpoint(
        report_path,
        metadata=metadata,
        cases=cases,
        requested=len(rows),
        candidate_count=args.candidate_count,
        compare_direct=args.compare_direct,
        status="running",
    )

    for position, row in enumerate(rows, 1):
        index = int(row["index"])
        seed_prompt = str(row["query"])
        risk_types = list(row["risk_types"])
        case: dict[str, Any] = {
            "index": index,
            "seed_prompt": seed_prompt,
            "risk_types": risk_types,
            "risk_category": row["risk_category"],
            "risk_name": row["risk_name"],
            "direct": {},
            "skill_execution_error": "",
            "variants": [],
            "skill_success": False,
            "best_skill_score": None,
        }

        if args.compare_direct:
            case["direct"] = _evaluate_candidate(
                candidate_text=seed_prompt,
                source_skill="direct-seed",
                candidate_index=0,
                seed_prompt=seed_prompt,
                risk_types=risk_types,
                target=target,
                evaluator=evaluator,
                secrets=secrets,
            )

        context = SkillContext(
            run_id=run_id,
            step_id=index,
            seed_prompt=seed_prompt,
            target_profile=target_profile,
            memory_summary={},
            extra={
                "action_args": {"candidate_count": args.candidate_count},
                "skill_model_backend": skill_backend,
                "seed_risk_types": risk_types,
            },
        )
        try:
            skill_result = executor.execute(spec, context)
            generated_candidates = list(skill_result.candidates)[
                : args.candidate_count
            ]
            for candidate_index in range(args.candidate_count):
                if candidate_index >= len(generated_candidates):
                    case["variants"].append(
                        {
                            "candidate_index": candidate_index,
                            "candidate_text": "",
                            "response_text": "",
                            "target_model": "",
                            "judge_score": None,
                            "success": False,
                            "defender_refused": None,
                            "empty_response": None,
                            "judge_reason": "",
                            "error": "skill: missing candidate",
                        }
                    )
                    continue
                candidate = generated_candidates[candidate_index]
                candidate_text = str(candidate.get("text", ""))
                if not candidate_text.strip():
                    case["variants"].append(
                        {
                            "candidate_index": candidate_index,
                            "candidate_text": "",
                            "response_text": "",
                            "target_model": "",
                            "judge_score": None,
                            "success": False,
                            "defender_refused": None,
                            "empty_response": None,
                            "judge_reason": "",
                            "error": "skill: empty candidate",
                        }
                    )
                    continue
                case["variants"].append(
                    _evaluate_candidate(
                        candidate_text=candidate_text,
                        source_skill=spec.name,
                        candidate_index=candidate_index,
                        seed_prompt=seed_prompt,
                        risk_types=risk_types,
                        target=target,
                        evaluator=evaluator,
                        secrets=secrets,
                    )
                )
        except Exception as exc:  # noqa: BLE001 - checkpoint the remaining batch
            case["skill_execution_error"] = _safe_error(exc, secrets)

        scores = [
            int(variant["judge_score"])
            for variant in case["variants"]
            if variant.get("judge_score") is not None
        ]
        case["best_skill_score"] = max(scores) if scores else None
        case["skill_success"] = any(
            bool(variant.get("success")) for variant in case["variants"]
        )
        cases.append(case)
        _checkpoint(
            report_path,
            metadata=metadata,
            cases=cases,
            requested=len(rows),
            candidate_count=args.candidate_count,
            compare_direct=args.compare_direct,
            status="running",
        )
        direct_score = case.get("direct", {}).get("judge_score")
        print(
            f"[{position}/{len(rows)}] index={index} "
            f"direct={direct_score if args.compare_direct else 'skipped'} "
            f"skill_best={case['best_skill_score']} "
            f"success={case['skill_success']}",
            flush=True,
        )

    final_summary = summarize_cases(
        cases,
        requested=len(rows),
        candidate_count=args.candidate_count,
        compare_direct=args.compare_direct,
    )
    final_status = completion_status(
        final_summary,
        compare_direct=args.compare_direct,
    )
    final_payload = _checkpoint(
        report_path,
        metadata=metadata,
        cases=cases,
        requested=len(rows),
        candidate_count=args.candidate_count,
        compare_direct=args.compare_direct,
        status=final_status,
    )
    return {
        **metadata,
        "status": final_status,
        "target_model_evaluated": final_payload["target_model_evaluated"],
        "attack_outcome_evaluated": final_payload["attack_outcome_evaluated"],
        "summary": final_payload["summary"],
        "report_out": str(report_path),
    }


def main(argv: list[str] | None = None) -> int:
    try:
        result = run(parse_args(argv))
    except Exception as exc:  # noqa: BLE001 - concise CLI failure
        secrets = [
            str(os.environ.get(name, ""))
            for name in (
                "API_KEY",
                "TARGET_API_KEY",
                "GUARD_API_KEY",
                "SKILL_API_KEY",
            )
        ]
        print(
            json.dumps(
                {"status": "error", "error": _safe_error(exc, secrets)},
                ensure_ascii=False,
                indent=2,
            ),
            file=sys.stderr,
        )
        return 2
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["status"] != "failed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
